language: java
jdk:
  - oraclejdk8
services: mysql
before_install:
  - mysql -e 'create database morn-test;'
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('bmeB4000') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root